name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Jinni and dependencies
      shell: pwsh # Explicitly use PowerShell
      run: |
        python -m pip install --upgrade pip # Ensure pip is available
        pip install uv
        uv venv .venv
        .\\.venv\\Scripts\\Activate.ps1 # Activate the venv
        uv pip install -e .[dev]        # Use global uv, install dev extras

    - name: Run tests
      run: pytest -v                # pure Windows tests

    # --- WSL Smoke Test Setup & Execution ---
    - name: Enable WSL + Ubuntu
      run: |
        wsl --install -d Ubuntu --no-launch
        wsl -d Ubuntu -u root -- echo "WSL Enabled"

    - name: Create sample project in WSL
      run: |
        wsl bash -c 'mkdir -p /home/runner/testproj && echo "hello" > /home/runner/testproj/hello.txt'

    - name: Smoke test vscode-remote URI
      run: |
        echo "Testing vscode-remote URI..."
        .\\.venv\\Scripts\\jinni --list-only vscode-remote://wsl+Ubuntu/home/runner/testproj | findstr hello.txt

    - name: Smoke test POSIX path
      run: |
        echo "Testing POSIX path..."
        .\\.venv\\Scripts\\jinni --list-only /home/runner/testproj | findstr hello.txt

    - name: Smoke test translated UNC path (should not re-translate)
      run: |
        echo "Testing already translated UNC path..."
        .\\.venv\\Scripts\\jinni --list-only '\\\\wsl$\\Ubuntu\\home\\runner\\testproj' | findstr hello.txt 