name: Windows CI
on:
  push:   {branches: [main]}
  pull_request: {branches: [main]}

jobs:
  build:
    runs-on: windows-latest
    env:
      VENV_DIR: .\.venv           # single source of truth
      VENV_BIN: .\.venv\Scripts   # helper so paths stay short

    steps:
    - uses: actions/checkout@v4

    - name: Set-up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # ────────────────────────────────────────────
    #  Create & populate the venv with uv + dev-deps
    # ────────────────────────────────────────────
    - name: Install deps with uv
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv $env:VENV_DIR          # creates the venv
        & $env:VENV_BIN\Activate.ps1   # enters the venv
        uv pip install -e .[dev]       # installs proj + pytest, pathspec, etc.

    # ────────────────────────────────────────────
    #  Run unit tests on host Windows
    # ────────────────────────────────────────────
    - name: Run pytest (host)
      shell: pwsh
      run: |
        & $env:VENV_BIN\Activate.ps1
        pytest -v

    # ────────────────────────────────────────────
    #  Provision WSL 2 (Ubuntu 22.04) once & keep
    # ────────────────────────────────────────────
    - name: Enable WSL (Ubuntu 22.04)
      uses: Vampire/setup-wsl@v5   # installs kernel if missing & updates it
      with:
        distribution: Ubuntu-22.04

    # ────────────────────────────────────────────
    #  Create a tiny project inside WSL we can read
    # ────────────────────────────────────────────
    - name: Create sample project in WSL
      shell: pwsh
      run: |
        wsl bash -c 'mkdir -p /home/runner/testproj && echo hi > /home/runner/testproj/hello.txt'

    # ────────────────────────────────────────────
    #  Smoke-tests jinni path translation from Windows
    # ────────────────────────────────────────────
    - name: Smoke test vscode-remote URI
      shell: pwsh
      run: |
        & $env:VENV_BIN\Activate.ps1
        & $env:VENV_BIN\jinni.exe --list-only `
          'vscode-remote://wsl+Ubuntu-22.04/home/runner/testproj' |
          Select-String 'hello.txt'

    - name: Smoke test POSIX path
      shell: pwsh
      run: |
        & $env:VENV_BIN\Activate.ps1
        & $env:VENV_BIN\jinni.exe --list-only '/home/runner/testproj' |
          Select-String 'hello.txt'

    - name: Smoke test UNC path (already translated)
      shell: pwsh
      run: |
        & $env:VENV_BIN\Activate.ps1
        & $env:VENV_BIN\jinni.exe --list-only '\\wsl$\Ubuntu-22.04\home\runner\testproj' |
          Select-String 'hello.txt' 